source 'https://rubygems.org'

# gem "jekyll", github: "jekyll/jekyll"
# gem "jekyll", ">= 3.6.3"
# gem "jekyll", "=3.8.5"
gem "jekyll", "<4.0.0"
gem "thin"
gem "kramdown", ">= 2.3.0"
gem "kramdown-parser-gfm" 
gem "csv" 
gem "base64" 
gem "bigdecimal" 
gem "logger" 
gem "webrick" 
gem "rack", ">= 2.2.3"
