#!/usr/bin/env python3
"""Generate the inline world-map country paths used by /travel-map/.

Reads the Natural Earth 110m admin-0 country boundaries (public domain) and
emits `_includes/world-map-paths.svg`: one `<path>` per country, keyed by its
ISO-3166 alpha-3 code, projected with a plain equirectangular (plate carree)
projection into a 2000 x 1000 coordinate space:

    x = (lon + 180) * (2000 / 360)
    y = (90  - lat) * (1000 / 180)

`_pages/travel-map.md` places its city markers with that same formula in Liquid,
so shapes and markers stay in register without any JavaScript at run time.

Usage:
    python3 scripts/build_world_map.py            # downloads the source once
    python3 scripts/build_world_map.py --source path/to/countries.geojson

The download is cached in scripts/.cache/ and is not committed; the generated
SVG is committed, so the site builds without ever re-running this.
"""

import argparse
import json
import os
import sys
import urllib.request

SOURCE_URL = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master"
    "/geojson/ne_110m_admin_0_countries.geojson"
)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(REPO, "scripts", ".cache", "ne_110m_admin_0_countries.geojson")
OUTPUT = os.path.join(REPO, "_includes", "world-map-paths.svg")

# Antarctica dominates the bottom third of an equirectangular map and carries no
# information here, so it is dropped rather than cropped.
SKIP = {"ATA"}

WIDTH, HEIGHT = 2000.0, 1000.0
PRECISION = 1  # ~0.05 px at the size the map is displayed


def fetch(source):
    if source:
        return source
    if not os.path.exists(CACHE):
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        sys.stderr.write("Downloading %s\n" % SOURCE_URL)
        urllib.request.urlretrieve(SOURCE_URL, CACHE)
    return CACHE


def project(lon, lat):
    return (lon + 180.0) * (WIDTH / 360.0), (90.0 - lat) * (HEIGHT / 180.0)


def fmt(value):
    """Trim trailing zeros so `1.0` serialises as `1`."""
    text = "%.*f" % (PRECISION, value)
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"


def ring_to_path(ring):
    """One closed ring as an `M`/`l` sub-path with relative line commands.

    Relative deltas keep the numbers small (most are under 10), which roughly
    halves the file size versus absolute coordinates. Points that round to the
    same place as their predecessor are dropped.
    """
    points = []
    for lon, lat in ring:
        x, y = project(lon, lat)
        point = (round(x, PRECISION), round(y, PRECISION))
        if not points or point != points[-1]:
            points.append(point)

    # A ring needs at least a triangle to be worth drawing.
    if len(points) < 3:
        return ""

    parts = ["M%s %s" % (fmt(points[0][0]), fmt(points[0][1]))]
    previous = points[0]
    deltas = []
    for point in points[1:]:
        deltas.append("%s %s" % (fmt(point[0] - previous[0]), fmt(point[1] - previous[1])))
        previous = point
    if deltas:
        parts.append("l" + ",".join(deltas))
    parts.append("Z")
    return "".join(parts)


def geometry_to_path(geometry):
    kind = geometry["type"]
    if kind == "Polygon":
        polygons = [geometry["coordinates"]]
    elif kind == "MultiPolygon":
        polygons = geometry["coordinates"]
    else:
        return ""

    subpaths = []
    for polygon in polygons:
        for ring in polygon:
            subpath = ring_to_path(ring)
            if subpath:
                subpaths.append(subpath)
    return "".join(subpaths)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", help="local GeoJSON instead of the cached download")
    parser.add_argument("--output", default=OUTPUT, help="path of the SVG fragment to write")
    args = parser.parse_args()

    with open(fetch(args.source), encoding="utf-8") as handle:
        data = json.load(handle)

    countries = {}
    for feature in data["features"]:
        iso = feature["properties"].get("ADM0_A3")
        if not iso or iso in SKIP:
            continue
        path = geometry_to_path(feature["geometry"])
        if not path:
            continue
        # A handful of ISO codes appear twice (dependencies sharing a sovereign);
        # merge them into a single path so ids stay unique.
        countries[iso] = countries.get(iso, "") + path

    lines = [
        "<!-- Generated by scripts/build_world_map.py - do not edit by hand.",
        "     Source: Natural Earth 110m admin-0 countries (public domain).",
        "     Equirectangular projection in a 2000x1000 coordinate space. -->",
    ]
    for iso in sorted(countries):
        lines.append('<path id="c-%s" d="%s"/>' % (iso, countries[iso]))

    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")

    size = os.path.getsize(args.output)
    sys.stderr.write("Wrote %s (%d countries, %.1f KB)\n" % (args.output, len(countries), size / 1024.0))


if __name__ == "__main__":
    main()
